import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/authOptions";
import { adminDb } from "@/lib/firebase-admin";
import speech from "@google-cloud/speech";

// Initialize the Speech client
const speechClient = new speech.SpeechClient({
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  credentials: {
    client_email: process.env.FIREBASE_CLIENT_EMAIL,
    private_key: process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n'),
  }
});

export async function POST(request: Request) {
  try {
    // Authenticate the user
    const session = await getServerSession(authOptions);
    if (!session || !session.user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const formData = await request.formData();
    const photoId = formData.get("photoId") as string;
    const photoUrl = formData.get("photoUrl") as string;
    const audioFile = formData.get("audio") as File;

    if (!photoId || !audioFile) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    // Convert audio file to base64 for Google Cloud Speech API
    const arrayBuffer = await audioFile.arrayBuffer();
    const audioBytes = Buffer.from(arrayBuffer).toString("base64");

    // Configure the STT request
    // Note: The encoding and sampleRateHertz might need adjustment based on the exact
    // format generated by the browser's MediaRecorder. WEBM_OPUS is typical for Chrome.
    const audio = {
      content: audioBytes,
    };
    
    const config = {
      encoding: 'WEBM_OPUS' as const,
      // Sample rate is usually 48000 for standard WebM Opus from MediaRecorder
      sampleRateHertz: 48000,
      languageCode: 'en-US',
    };

    const speechRequest = {
      audio: audio,
      config: config,
    };

    // Call the Speech-to-Text API
    const [response] = await speechClient.recognize(speechRequest);
    
    const transcription = response.results
      ?.map(result => result.alternatives?.[0].transcript)
      .join('\n') || "";

    if (!transcription) {
      return NextResponse.json({ error: "Could not transcribe audio" }, { status: 400 });
    }

    // Save the memory context to Firestore
    const memoryDoc = {
      photoId,
      photoUrl,
      caretakerEmail: session.user.email,
      caretakerName: session.user.name,
      transcription,
      createdAt: new Date().toISOString(),
      status: 'active', // ready for the Magic Frame
    };

    await adminDb.collection("memories").doc(photoId).set(memoryDoc, { merge: true });

    return NextResponse.json({ success: true, transcription });
  } catch (error: any) {
    console.error("Upload Voice Error:", error);
    return NextResponse.json(
      { error: error.message || "Failed to process audio" },
      { status: 500 }
    );
  }
}
